# Generated by Django 5.2.16 on 2026-08-03 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=96)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=500)),
                ('destination_route', models.CharField(blank=True, max_length=96)),
                ('destination_kwargs', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notify_recipient_read_idx'), models.Index(fields=['recipient', '-created_at'], name='notify_recipient_created_idx'), models.Index(fields=['event_type', '-created_at'], name='notify_type_created_idx')],
            },
        ),
    ]
