# Generated by Django 5.2.16 on 2026-07-24 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=96)),
                ('payload', models.JSONField(default=dict)),
                ('aggregate_type', models.CharField(max_length=96)),
                ('aggregate_reference', models.CharField(max_length=128)),
                ('available_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('available_at', 'created_at'),
                'indexes': [models.Index(fields=['processed_at', 'failed_at', 'available_at'], name='core_outbox_ready_idx'), models.Index(fields=['locked_at'], name='core_outbox_lease_idx'), models.Index(fields=['event_type', 'created_at'], name='core_outbox_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='core.outboxevent')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['event', '-started_at'], name='core_attempt_event_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'attempt_number'), name='core_outbox_attempt_unique')],
            },
        ),
    ]
