# Generated by Django 5.2.16 on 2026-07-24 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_alter_moderationaction_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(choices=[('scam', 'Scam or fraud'), ('prohibited', 'Prohibited item or service'), ('stolen_counterfeit', 'Suspected stolen or counterfeit item'), ('inaccurate', 'Inaccurate or misleading'), ('abuse_other', 'Abuse or other concern')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('source_ip_hash', models.CharField(db_index=True, max_length=64)),
                ('duplicate_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listing_reports', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], max_length=16)),
                ('from_state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], max_length=16)),
                ('to_state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], max_length=16)),
                ('internal_note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_report_actions', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_report_action_assignments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='reports.listingreport')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['state', 'created_at'], name='reports_state_created'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['listing', 'created_at'], name='reports_listing_created'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['reporter', 'created_at'], name='reports_reporter_created'),
        ),
        migrations.AddIndex(
            model_name='listingreportaction',
            index=models.Index(fields=['report', 'created_at'], name='reports_action_report_at'),
        ),
    ]
