# Generated by Django 5.2.16 on 2026-07-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingreport',
            options={'permissions': [('triage_listingreport', 'Can triage listing reports')]},
        ),
    ]
