# Generated by Django 5.2.16 on 2026-07-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('billing', '0001_initial'),
        ('listings', '0010_remove_listing_listings_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('new_listing', 'New listing'), ('renewal', 'Renewal')], default='new_listing', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('purpose', 'renewal'), ('status', 'pending')), fields=('listing', 'purpose'), name='billing_one_pending_renewal'),
        ),
    ]
