# Generated by Django 5.2.16 on 2026-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_purpose_order_billing_one_pending_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('payment_failed', 'Payment failed'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
