# Generated by Django 5.2.16 on 2026-07-24 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_alter_moderationaction_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('refunds', 'Refunds'), ('prohibited_items', 'Prohibited items'), ('content_rights', 'Content rights'), ('communications', 'Communications')], max_length=32)),
                ('version', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('requires_listing_acceptance', models.BooleanField(default=True)),
                ('legal_entity_name', models.CharField(blank=True, max_length=200)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('kind', '-version'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='policies_kind_version_unique'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('kind',), name='policies_one_active_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='policies.policydocument')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'document'], name='policies_acceptance_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'user', 'listing'), name='policies_acceptance_unique')],
            },
        ),
    ]
