# Generated by Django 5.2.16 on 2026-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policydocument',
            constraint=models.CheckConstraint(condition=models.Q(('legal_entity_name', ''), ('status', 'active'), _negated=True), name='policies_active_entity_required'),
        ),
    ]
