# Generated by Django 5.2.16 on 2026-07-23 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2, unique=True)),
                ('usps_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_network_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('fips__regex', '^\\d{2}$')), name='locations_state_fips'), models.CheckConstraint(condition=models.Q(('usps_code__regex', '^[A-Z]{2}$')), name='locations_state_usps_code')],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_network_enabled', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='locations.state')),
            ],
            options={
                'ordering': ('state__name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('state', 'slug'), name='locations_county_state_slug_unique'), models.CheckConstraint(condition=models.Q(('fips__regex', '^\\d{5}$')), name='locations_county_fips')],
            },
        ),
    ]
