# Generated by Django 5.2.16 on 2026-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_county_state_fips_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('release_version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('transformation_version', models.CharField(max_length=50)),
                ('source_state_count', models.PositiveIntegerField()),
                ('source_county_count', models.PositiveIntegerField()),
                ('states_created_count', models.PositiveIntegerField()),
                ('states_updated_count', models.PositiveIntegerField()),
                ('states_unchanged_count', models.PositiveIntegerField()),
                ('counties_created_count', models.PositiveIntegerField()),
                ('counties_updated_count', models.PositiveIntegerField()),
                ('counties_unchanged_count', models.PositiveIntegerField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-imported_at',),
            },
        ),
    ]
