# Generated by Django 5.2.16 on 2026-07-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_referenceimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCountyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=5)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('release_version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('transformation_version', models.CharField(max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zip_candidates', to='locations.county')),
            ],
            options={
                'ordering': ('postal_code', 'county__name'),
                'indexes': [models.Index(fields=['postal_code', 'county'], name='locations_zip_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('postal_code', 'county'), name='locations_zip_county_unique'), models.CheckConstraint(condition=models.Q(('postal_code__regex', '^\\d{5}$')), name='locations_zip_code_format')],
            },
        ),
    ]
