# Generated by Django 5.2.16 on 2026-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_zipcountyreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='centroid_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Public Census county internal-point latitude; not seller location data.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='centroid_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Public Census county internal-point longitude; not seller location data.', max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['centroid_latitude', 'centroid_longitude'], name='locations_county_centroid_idx'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.CheckConstraint(condition=models.Q(('centroid_latitude__isnull', True), models.Q(('centroid_latitude__gte', -90), ('centroid_latitude__lte', 90)), _connector='OR'), name='locations_county_centroid_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.CheckConstraint(condition=models.Q(('centroid_longitude__isnull', True), models.Q(('centroid_longitude__gte', -180), ('centroid_longitude__lte', 180)), _connector='OR'), name='locations_county_centroid_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('centroid_latitude__isnull', True), ('centroid_longitude__isnull', True)), models.Q(('centroid_latitude__isnull', False), ('centroid_longitude__isnull', False)), _connector='OR'), name='locations_county_centroid_pair'),
        ),
    ]
