# Generated by Django 5.2.16 on 2026-07-24 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='AccountSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('account_suspended', 'Account suspended'), ('account_restored', 'Account restored'), ('account_closed', 'Account closed'), ('staff_privilege_changed', 'Staff privilege changed')], db_index=True, max_length=40)),
                ('request_ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['subject', 'occurred_at'], name='accounts_security_subject_at'), models.Index(fields=['event_type', 'occurred_at'], name='accounts_security_type_at')],
            },
        ),
    ]
