# Generated by Django 5.2.16 on 2026-08-04

import uuid
from typing import Any

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_seller_profile_public_ids(
    apps: Any, schema_editor: Any
) -> None:
    seller_profile = apps.get_model("accounts", "SellerProfile")
    for profile in seller_profile.objects.filter(public_id__isnull=True).iterator():
        profile.public_id = uuid.uuid4()
        profile.save(update_fields=("public_id",))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_account_status_accountsecurityevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name="SellerProfileRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                (
                    "website_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                (
                    "x_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("review_note", models.TextField(blank=True, max_length=2000)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_seller_profile_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
                "indexes": [
                    models.Index(
                        fields=["seller_profile", "status", "submitted_at"],
                        name="acct_profile_revision_queue",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="current_approved_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.sellerprofilerevision",
            ),
        ),
        migrations.RunPython(populate_seller_profile_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sellerprofile",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
