# Generated by Django 5.2.16 on 2026-08-04 21:59

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile_public_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofilerevision',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.seller_profile_avatar_path),
        ),
    ]
