# Generated by Django 5.2.16 on 2026-07-23 18:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.county')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='accounts.sellerprofile')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.state')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.vertical')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AutoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('suv', 'SUV'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(9999)])),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('trim', models.CharField(blank=True, max_length=80)),
                ('mileage', models.PositiveIntegerField()),
                ('title_status', models.CharField(choices=[('clean', 'Clean'), ('salvage', 'Salvage'), ('rebuilt', 'Rebuilt'), ('other', 'Other')], max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$')])),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_details', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='listings_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'state', 'county'], name='listings_browse_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('price_minor__isnull', True)), models.Q(('currency__regex', '^[A-Z]{3}$'), ('price_minor__isnull', False)), _connector='OR'), name='listings_price_currency_pair'),
        ),
        migrations.AddConstraint(
            model_name='autodetails',
            constraint=models.CheckConstraint(condition=models.Q(('mileage__gte', 0)), name='listings_auto_mileage_nonnegative'),
        ),
    ]
