# Generated by Django 5.2.16 on 2026-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('catalog', '0005_product_price_postgresql_integrity'),
        ('listings', '0003_protect_auto_listing_vertical'),
        ('locations', '0003_referenceimport'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='listings_draft_status_only',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_browse_scope_idx',
        ),
        migrations.AddField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'state', 'county', 'category', '-published_at'], name='listings_public_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'vertical', 'category'], name='listings_public_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published'])), name='listings_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'draft')), models.Q(('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='listings_status_published_at_pair'),
        ),
    ]
