# Generated by Django 5.2.16 on 2026-07-23 22:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


CREATE_POSTGRESQL_INTEGRITY_SQL = """
CREATE OR REPLACE FUNCTION listings_validate_listing_relations() RETURNS trigger AS $$
BEGIN
    IF NEW.vertical_id != (SELECT vertical_id FROM catalog_category WHERE id = NEW.category_id) THEN
        RAISE EXCEPTION 'listing category must belong to listing vertical';
    END IF;
    IF NEW.state_id != (SELECT state_id FROM locations_county WHERE id = NEW.county_id) THEN
        RAISE EXCEPTION 'listing county must belong to listing state';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_autodetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'autos' THEN
        RAISE EXCEPTION 'an automobile listing must retain the Autos vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_homedetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'real-estate' THEN
        RAISE EXCEPTION 'a home listing must retain the Real Estate vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_rentaldetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'rentals' THEN
        RAISE EXCEPTION 'a rental listing must retain the Rentals vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION listings_validate_home_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) != 'real-estate' THEN
        RAISE EXCEPTION 'home details require the Real Estate vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_home_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_homedetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_home_vertical();

CREATE FUNCTION listings_validate_rental_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) != 'rentals' THEN
        RAISE EXCEPTION 'rental details require the Rentals vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_rental_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_rentaldetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_rental_vertical();
"""

REVERSE_POSTGRESQL_INTEGRITY_SQL = """
DROP TRIGGER IF EXISTS listings_home_vertical_trigger ON listings_homedetails;
DROP FUNCTION IF EXISTS listings_validate_home_vertical();
DROP TRIGGER IF EXISTS listings_rental_vertical_trigger ON listings_rentaldetails;
DROP FUNCTION IF EXISTS listings_validate_rental_vertical();
CREATE OR REPLACE FUNCTION listings_validate_listing_relations() RETURNS trigger AS $$
BEGIN
    IF NEW.vertical_id != (SELECT vertical_id FROM catalog_category WHERE id = NEW.category_id) THEN
        RAISE EXCEPTION 'listing category must belong to listing vertical';
    END IF;
    IF NEW.state_id != (SELECT state_id FROM locations_county WHERE id = NEW.county_id) THEN
        RAISE EXCEPTION 'listing county must belong to listing state';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_autodetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'autos' THEN
        RAISE EXCEPTION 'an automobile listing must retain the Autos vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def create_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREATE_POSTGRESQL_INTEGRITY_SQL)


def reverse_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_POSTGRESQL_INTEGRITY_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_listings_draft_status_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=160)),
                ('address_line_2', models.CharField(blank=True, max_length=160)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('general_area', models.CharField(max_length=160)),
                ('exact_address_public', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('manufactured_home', 'Manufactured home'), ('land', 'Land'), ('multifamily', 'Multifamily'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lot_size_unit', models.CharField(blank=True, choices=[('acres', 'Acres'), ('square_feet', 'Square feet')], max_length=20)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_details', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('beds__gte', 0), ('beds__isnull', True), _connector='OR'), name='listings_home_beds_nonnegative'), models.CheckConstraint(condition=models.Q(('baths__gte', 0), ('baths__isnull', True), _connector='OR'), name='listings_home_baths_nonnegative'), models.CheckConstraint(condition=models.Q(('square_feet__gte', 0), ('square_feet__isnull', True), _connector='OR'), name='listings_home_sqft_nonnegative'), models.CheckConstraint(condition=models.Q(('lot_size__gte', 0), ('lot_size__isnull', True), _connector='OR'), name='listings_home_lot_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('lot_size__isnull', True), ('lot_size_unit', '')), models.Q(('lot_size__isnull', False), ('lot_size_unit__in', ('acres', 'square_feet'))), _connector='OR'), name='listings_home_lot_unit_pair')],
            },
        ),
        migrations.CreateModel(
            name='RentalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=160)),
                ('address_line_2', models.CharField(blank=True, max_length=160)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('general_area', models.CharField(max_length=160)),
                ('exact_address_public', models.BooleanField(default=False)),
                ('rental_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('room', 'Room'), ('manufactured_home', 'Manufactured home'), ('vacation', 'Vacation'), ('commercial', 'Commercial'), ('storage', 'Storage'), ('other', 'Other')], max_length=20)),
                ('monthly_rent_minor', models.PositiveBigIntegerField()),
                ('security_deposit_minor', models.PositiveBigIntegerField(default=0)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_date', models.DateField()),
                ('pets_policy', models.CharField(choices=[('allowed', 'Pets allowed'), ('not_allowed', 'No pets'), ('case_by_case', 'Case by case')], max_length=20)),
                ('lease_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flexible_term', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_details', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_rent_minor__gte', 0)), name='listings_rental_rent_nonnegative'), models.CheckConstraint(condition=models.Q(('security_deposit_minor__gte', 0)), name='listings_rental_deposit_nonnegative'), models.CheckConstraint(condition=models.Q(('beds__gte', 0), ('beds__isnull', True), _connector='OR'), name='listings_rental_beds_nonnegative'), models.CheckConstraint(condition=models.Q(('baths__gte', 0), ('baths__isnull', True), _connector='OR'), name='listings_rental_baths_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('flexible_term', True), ('lease_term_months__isnull', True)), models.Q(('flexible_term', False), ('lease_term_months__gte', 1)), _connector='OR'), name='listings_rental_lease_term')],
            },
        ),
        migrations.RunPython(create_postgresql_integrity, reverse_postgresql_integrity),
    ]
