# Generated by Django 5.2.16 on 2026-07-23 22:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


CREATE_POSTGRESQL_INTEGRITY_SQL = """
CREATE OR REPLACE FUNCTION listings_validate_listing_relations() RETURNS trigger AS $$
BEGIN
    IF NEW.vertical_id != (SELECT vertical_id FROM catalog_category WHERE id = NEW.category_id) THEN
        RAISE EXCEPTION 'listing category must belong to listing vertical';
    END IF;
    IF NEW.state_id != (SELECT state_id FROM locations_county WHERE id = NEW.county_id) THEN
        RAISE EXCEPTION 'listing county must belong to listing state';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_autodetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'autos' THEN
        RAISE EXCEPTION 'an automobile listing must retain the Autos vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_homedetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'real-estate' THEN
        RAISE EXCEPTION 'a home listing must retain the Real Estate vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_rentaldetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'rentals' THEN
        RAISE EXCEPTION 'a rental listing must retain the Rentals vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_agequipmentdetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'farm-ranch' THEN
        RAISE EXCEPTION 'agricultural equipment listings must retain the Farm & Ranch vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_livestockdetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'livestock-animals' THEN
        RAISE EXCEPTION 'livestock listings must retain the Livestock & Animals vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_pasturedetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'farm-ranch' THEN
        RAISE EXCEPTION 'pasture listings must retain the Farm & Ranch vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION listings_validate_ag_equipment_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) != 'farm-ranch' THEN
        RAISE EXCEPTION 'agricultural equipment details require the Farm & Ranch vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_ag_equipment_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_agequipmentdetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_ag_equipment_vertical();

CREATE FUNCTION listings_validate_livestock_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) != 'livestock-animals' THEN
        RAISE EXCEPTION 'livestock details require the Livestock & Animals vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_livestock_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_livestockdetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_livestock_vertical();

CREATE FUNCTION listings_validate_pasture_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) != 'farm-ranch' THEN
        RAISE EXCEPTION 'pasture details require the Farm & Ranch vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_pasture_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_pasturedetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_pasture_vertical();
"""

REVERSE_POSTGRESQL_INTEGRITY_SQL = """
DROP TRIGGER IF EXISTS listings_ag_equipment_vertical_trigger ON listings_agequipmentdetails;
DROP FUNCTION IF EXISTS listings_validate_ag_equipment_vertical();
DROP TRIGGER IF EXISTS listings_livestock_vertical_trigger ON listings_livestockdetails;
DROP FUNCTION IF EXISTS listings_validate_livestock_vertical();
DROP TRIGGER IF EXISTS listings_pasture_vertical_trigger ON listings_pasturedetails;
DROP FUNCTION IF EXISTS listings_validate_pasture_vertical();
CREATE OR REPLACE FUNCTION listings_validate_listing_relations() RETURNS trigger AS $$
BEGIN
    IF NEW.vertical_id != (SELECT vertical_id FROM catalog_category WHERE id = NEW.category_id) THEN
        RAISE EXCEPTION 'listing category must belong to listing vertical';
    END IF;
    IF NEW.state_id != (SELECT state_id FROM locations_county WHERE id = NEW.county_id) THEN
        RAISE EXCEPTION 'listing county must belong to listing state';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_autodetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'autos' THEN
        RAISE EXCEPTION 'an automobile listing must retain the Autos vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_homedetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'real-estate' THEN
        RAISE EXCEPTION 'a home listing must retain the Real Estate vertical';
    END IF;
    IF EXISTS (SELECT 1 FROM listings_rentaldetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id) != 'rentals' THEN
        RAISE EXCEPTION 'a rental listing must retain the Rentals vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def create_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREATE_POSTGRESQL_INTEGRITY_SQL)


def reverse_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_POSTGRESQL_INTEGRITY_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_homedetails_rentaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgEquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('tractor', 'Tractor'), ('harvesting', 'Harvesting equipment'), ('implement', 'Implement'), ('ranch_supply', 'Ranch supply'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('powered', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('for_parts', 'For parts')], max_length=20)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ag_equipment_details', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hours__gte', 0), ('hours__isnull', True), _connector='OR'), name='listings_ag_equipment_hours_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='LivestockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goats_sheep', 'Goats & sheep'), ('horses', 'Horses'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('animal_class', models.CharField(blank=True, max_length=100)),
                ('head_count', models.PositiveIntegerField()),
                ('age_or_weight', models.CharField(blank=True, max_length=120)),
                ('sale_unit', models.CharField(choices=[('head', 'Per head'), ('group', 'As a group'), ('pound', 'Per pound')], max_length=20)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_details', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('head_count__gte', 1)), name='listings_livestock_head_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='PastureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('water_available', models.BooleanField(default=False)),
                ('fenced', models.BooleanField(default=False)),
                ('lease_term', models.CharField(max_length=100)),
                ('use_restrictions', models.CharField(blank=True, max_length=300)),
                ('available_date', models.DateField()),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasture_details', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('acreage__gt', 0)), name='listings_pasture_acreage_positive')],
            },
        ),
        migrations.RunPython(create_postgresql_integrity, reverse_postgresql_integrity),
    ]
