# Generated by Django 5.2.16 on 2026-07-23 22:18

import django.db.models.deletion
from django.db import migrations, models


CREATE_POSTGRESQL_INTEGRITY_SQL = """
CREATE FUNCTION listings_validate_home_goods_vertical() RETURNS trigger AS $$
BEGIN
    IF (SELECT slug FROM catalog_vertical v
        JOIN listings_listing l ON l.vertical_id = v.id
        WHERE l.id = NEW.listing_id) NOT IN ('appliances', 'home-garden') THEN
        RAISE EXCEPTION 'home goods details require the Appliances or Home & Garden vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_home_goods_vertical_trigger
BEFORE INSERT OR UPDATE OF listing_id ON listings_homegoodsdetails
FOR EACH ROW EXECUTE FUNCTION listings_validate_home_goods_vertical();

CREATE FUNCTION listings_prevent_incompatible_home_goods_vertical() RETURNS trigger AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM listings_homegoodsdetails WHERE listing_id = NEW.id)
       AND (SELECT slug FROM catalog_vertical WHERE id = NEW.vertical_id)
           NOT IN ('appliances', 'home-garden') THEN
        RAISE EXCEPTION 'a home goods listing must retain an Appliances or Home & Garden vertical';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER listings_home_goods_listing_vertical_trigger
BEFORE UPDATE OF vertical_id ON listings_listing
FOR EACH ROW EXECUTE FUNCTION listings_prevent_incompatible_home_goods_vertical();
"""

REVERSE_POSTGRESQL_INTEGRITY_SQL = """
DROP TRIGGER IF EXISTS listings_home_goods_listing_vertical_trigger ON listings_listing;
DROP FUNCTION IF EXISTS listings_prevent_incompatible_home_goods_vertical();
DROP TRIGGER IF EXISTS listings_home_goods_vertical_trigger ON listings_homegoodsdetails;
DROP FUNCTION IF EXISTS listings_validate_home_goods_vertical();
"""


def create_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREATE_POSTGRESQL_INTEGRITY_SQL)


def reverse_postgresql_integrity(apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_POSTGRESQL_INTEGRITY_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_agequipmentdetails_livestockdetails_pasturedetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeGoodsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item_type", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=80)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like new"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("for_parts", "For parts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "working_status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("not_working", "Not working"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=120)),
                (
                    "fulfillment_preference",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("either", "Pickup or delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_goods_details",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_postgresql_integrity, reverse_postgresql_integrity),
    ]
