# Generated by Django 5.2.16 on 2026-07-23 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('catalog', '0005_product_price_postgresql_integrity'),
        ('listings', '0007_homegoodsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.listingkind'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('expired', 'Expired')], default='open', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('staged_key', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='accounts.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordering', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('deleted', 'Deleted')], default='ready', max_length=16)),
                ('content_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('rendition_key', models.CharField(max_length=300, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
                ('upload_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='listing_image', to='listings.uploadsession')),
            ],
            options={
                'ordering': ('ordering', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ListingMediaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_image_count', models.PositiveSmallIntegerField(default=0)),
                ('maximum_image_count', models.PositiveSmallIntegerField(default=12)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_policy', to='catalog.category')),
                ('listing_kind', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_policy', to='catalog.listingkind')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('listing_kind__isnull', False)), models.Q(('category__isnull', False), ('listing_kind__isnull', True)), _connector='OR'), name='listings_media_policy_one_target'), models.CheckConstraint(condition=models.Q(('maximum_image_count__gte', 1)), name='listings_media_policy_max_positive'), models.CheckConstraint(condition=models.Q(('required_image_count__lte', models.F('maximum_image_count'))), name='listings_media_policy_required_within_max')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['state', 'expires_at'], name='listings_upload_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['listing', 'seller'], name='listings_upload_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'state', 'ordering'], name='listings_image_listing_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ready')), fields=('listing', 'ordering'), name='listings_ready_image_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 1), ('height__gte', 1), ('width__gte', 1)), name='listings_image_dimensions_positive'),
        ),
    ]
