# Generated by Django 5.2.16 on 2026-07-23 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('catalog', '0005_product_price_postgresql_integrity'),
        ('listings', '0008_listing_listing_kind_uploadsession_listingimage_and_more'),
        ('locations', '0003_referenceimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submitted', 'Submitted'), ('claimed', 'Claimed'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('suspended', 'Suspended'), ('policy_flagged', 'Policy flagged'), ('direct_approval', 'Direct demo approval')], max_length=32)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=32)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=32)),
                ('internal_note', models.TextField(blank=True)),
                ('seller_facing_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModerationReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('seller_facing_text', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_escalation', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('category', 'code'),
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-updated_at',), 'permissions': [('moderate_listing', 'Can moderate listings')]},
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='listings_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='listings_status_published_at_pair',
        ),
        migrations.AddField(
            model_name='listing',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listing_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='lifecycle_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='listings_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'in_review', 'published', 'changes_requested', 'rejected', 'suspended'])), name='listings_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status__in', ('draft', 'submitted', 'in_review', 'changes_requested', 'rejected', 'suspended'))), models.Q(('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='listings_status_published_at_pair'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='moderationreasoncode',
            index=models.Index(fields=['is_active', 'category'], name='moderation_reason_active_idx'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='listings.moderationreasoncode'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['listing', '-created_at'], name='moderation_action_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='moderation_action_type_idx'),
        ),
    ]
