# Generated by Django 5.2.16 on 2026-07-23 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
        ('catalog', '0006_listingproduct_duration_days'),
        ('listings', '0009_moderationaction_moderationreasoncode_and_more'),
        ('locations', '0003_referenceimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='listings_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='listings_status_published_at_pair',
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_payment', 'Awaiting payment'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='from_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_payment', 'Awaiting payment'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_payment', 'Awaiting payment'), ('in_review', 'In review'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'awaiting_payment', 'in_review', 'published', 'changes_requested', 'rejected', 'suspended'])), name='listings_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status__in', ('draft', 'submitted', 'awaiting_payment', 'in_review', 'changes_requested', 'rejected', 'suspended'))), models.Q(('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='listings_status_published_at_pair'),
        ),
    ]
