# Generated by Django 5.2.16 on 2026-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_favorite_remove_listing_listings_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('claimed', 'Claimed'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('suspended', 'Suspended'), ('policy_flagged', 'Policy flagged'), ('direct_approval', 'Direct demo approval'), ('material_edit', 'Material edit submitted'), ('marked_sold', 'Marked sold'), ('archived', 'Archived'), ('restored_draft', 'Restored to draft'), ('renewed', 'Renewed'), ('expired', 'Expired')], max_length=32),
        ),
    ]
