# Generated by Django 5.2.16 on 2026-07-24 04:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_moderationaction_action_type'),
        ('locations', '0004_zipcountyreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_mode', models.CharField(choices=[('fixed', 'Fixed price'), ('negotiable', 'Negotiable'), ('contact', 'Contact for price'), ('free', 'Free')], max_length=16)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')])),
                ('street_address', models.CharField(blank=True, max_length=160)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generic_details', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingCountyPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_listings', to='locations.county')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_counties', to='listings.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'county'), name='listings_additional_county_unique')],
            },
        ),
    ]
