# Generated by Django 5.2.16 on 2026-07-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_search_document_and_placement_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericlistingdetails',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='genericlistingdetails',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
