# Generated by Django 5.2.16 on 2026-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_genericlistingdetails_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='broker_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
