# Generated by Django 5.2.16 on 2026-07-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_catalogpostingprofile_catalogpostingfield'),
        ('listings', '0016_listing_broker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_tags', to='catalog.category')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_tags', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'listing'], name='listings_controlled_tag_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'category'), name='listings_controlled_tag_unique')],
            },
        ),
        migrations.CreateModel(
            name='ListingCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('normalized_label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=500)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='listings.listing')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('listing', 'normalized_label'), name='listings_custom_field_label_unique')],
            },
        ),
        migrations.CreateModel(
            name='ListingSellerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('normalized_value', models.CharField(max_length=40)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_tags', to='listings.listing')),
            ],
            options={
                'ordering': ('normalized_value',),
                'indexes': [models.Index(fields=['normalized_value', 'listing'], name='listings_seller_tag_search_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'normalized_value'), name='listings_seller_tag_unique')],
            },
        ),
    ]
