# Generated by Django 5.2.16 on 2026-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listingcategorytag_listingcustomfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcustomfield',
            name='normalized_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='listingsellertag',
            name='normalized_value',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
