# Generated by Django 5.2.16 on 2026-08-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_ready_images(apps, schema_editor):
    ListingImage = apps.get_model("listings", "ListingImage")
    ListingImage.objects.filter(state="ready").update(moderation_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_intent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listing_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.RunPython(approve_existing_ready_images, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='moderationaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('claimed', 'Claimed'), ('approved', 'Approved'), ('approved_no_payment', 'Approved without payment'), ('approved_send_payment_link', 'Approved and sent payment link'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('image_approved', 'Image approved'), ('image_rejected', 'Image rejected'), ('escalated', 'Escalated'), ('suspended', 'Suspended'), ('policy_flagged', 'Policy flagged'), ('direct_approval', 'Direct demo approval'), ('material_edit', 'Material edit submitted'), ('marked_sold', 'Marked sold'), ('archived', 'Archived'), ('restored_draft', 'Restored to draft'), ('renewed', 'Renewed'), ('expired', 'Expired')], max_length=32),
        ),
    ]
