# Generated by Django 5.2.16 on 2026-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listingimage_moderated_at_listingimage_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_available',
            field=models.BooleanField(default=False),
        ),
    ]
