# Generated by Django 5.2.16 on 2026-08-07 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_listing_seller_feed_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('claimed', 'Claimed'), ('approved', 'Approved'), ('approved_no_payment', 'Approved without payment'), ('approved_send_payment_link', 'Approved and sent payment link'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('image_approved', 'Image approved'), ('image_rejected', 'Image rejected'), ('video_approved', 'Video approved'), ('video_rejected', 'Video rejected'), ('escalated', 'Escalated'), ('suspended', 'Suspended'), ('policy_flagged', 'Policy flagged'), ('direct_approval', 'Direct demo approval'), ('material_edit', 'Material edit submitted'), ('marked_sold', 'Marked sold'), ('archived', 'Archived'), ('restored_draft', 'Restored to draft'), ('renewed', 'Renewed'), ('expired', 'Expired')], max_length=32),
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('deleted', 'Deleted')], default='ready', max_length=16)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('moderation_reason', models.CharField(blank=True, max_length=500)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.listing')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listing_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['listing', 'state'], name='listings_video_listing_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gte', 1)), name='listings_video_byte_size_positive')],
            },
        ),
    ]
