# Generated by Django 5.2.16 on 2026-07-23 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_parent_vertical_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_kinds', to='catalog.vertical')),
            ],
            options={
                'ordering': ('vertical__display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ListingKindPriceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_mode', models.CharField(choices=[('fixed', 'Fixed price'), ('negotiable', 'Negotiable'), ('contact', 'Contact for price'), ('free', 'Free')], max_length=16)),
                ('listing_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supported_price_modes', to='catalog.listingkind')),
            ],
            options={
                'ordering': ('listing_kind', 'price_mode'),
            },
        ),
        migrations.CreateModel(
            name='ListingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9_-]*$')])),
                ('use_case', models.CharField(choices=[('new_listing', 'New listing'), ('renewal', 'Renewal')], max_length=16)),
                ('price_mode', models.CharField(choices=[('fixed', 'Fixed price'), ('negotiable', 'Negotiable'), ('contact', 'Contact for price'), ('free', 'Free')], max_length=16)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('listing_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.listingkind')),
            ],
            options={
                'ordering': ('listing_kind', 'use_case', 'price_mode', 'product_code'),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.listingproduct')),
            ],
            options={
                'ordering': ('product', 'currency', '-effective_from'),
            },
        ),
        migrations.AddConstraint(
            model_name='listingkind',
            constraint=models.UniqueConstraint(fields=('vertical', 'name'), name='catalog_listing_kind_vertical_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='listingkindpricemode',
            constraint=models.UniqueConstraint(fields=('listing_kind', 'price_mode'), name='catalog_listing_kind_price_mode_unique'),
        ),
        migrations.AddConstraint(
            model_name='listingproduct',
            constraint=models.UniqueConstraint(fields=('listing_kind', 'use_case', 'price_mode'), name='catalog_product_kind_use_case_mode_unique'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'currency', 'effective_from'], name='catalog_price_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='catalog_product_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='catalog_product_price_valid_window'),
        ),
    ]
