# Generated by Django 5.2.16 on 2026-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_listingkind_listingkindpricemode_listingproduct_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='catalog_product_price_currency_iso'),
        ),
    ]
