# Generated by Django 5.2.16 on 2026-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_price_postgresql_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingproduct',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
