# Generated by Django 5.2.16 on 2026-07-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_listingproduct_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingproduct',
            name='is_generic_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingproduct',
            name='listing_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.listingkind'),
        ),
        migrations.AddConstraint(
            model_name='listingproduct',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_generic_distribution', False), ('listing_kind__isnull', False)), models.Q(('is_generic_distribution', True), ('listing_kind__isnull', True)), _connector='OR'), name='catalog_product_generic_target'),
        ),
    ]
