# Generated by Django 5.2.16 on 2026-07-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_listingproduct_is_generic_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPostingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posting_profile', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPostingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Whole number'), ('boolean', 'Yes or no'), ('choice', 'Choice')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('owner_only', 'Owner only'), ('staff_only', 'Staff only')], default='public', max_length=16)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('maximum', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_material', models.BooleanField(default=True)),
                ('allow_public_search', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='catalog.catalogpostingprofile')),
            ],
            options={
                'ordering': ('display_order', 'key'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'key'), name='catalog_posting_field_profile_key_unique')],
            },
        ),
    ]
